[theme]
theme = "solarized-dark"
[icons]
icons = "awesome5"
[icons.overrides]
bat = "| |"
bat_full = "|#|"
bat_charging = "|^|"
bat_discharging = "|v|"
backlight = "O"

[[block]]
block = "disk_space"
path = "/"
#alias = "/"
info_type = "available"
#unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
#driver = "upower"
#device = "BAT1"
format = "$icon $percentage $time "
full_format = "Full"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "backlight"

#[[block]]
#block = "sound"
#show_volume_when_muted = true

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %Y.%m.%d %R') "


