theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
#driver = "upower"
#device = "BAT1"
format = "{percentage} {time}"
full_format = "Full"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "backlight"

#[[block]]
#block = "sound"
#show_volume_when_muted = true

[[block]]
block = "time"
interval = 60
format = "%a %d.%m.%y %R"


